### ISSUE TITLE
bundle: nice UX around disconnected setup

### ISSUE THREAD

**Issue by estroz** [openshift/ocp-release-operator-sdk#113]
#### Describe the problem you need a feature to resolve.

A bundle's CSV supports "related image" configuration at the catalog level, which effectively establishes a pointer from some static image label to a resolved (i.e. contains the image's remote digest) image tag. Such config is crucial for disconnected clusters due to image proxying.

Related image config can be done via `.spec.relatedImages` (see #https://github.com/operator-framework/operator-sdk/issues/4884) or setting a `RELATED_IMAGE_{name}` [environment variable](https://osbs.readthedocs.io/en/latest/users.html?#creating-the-relatedimages-section). The latter is recommended, since OSBS will populate `.spec.relatedImages` from env vars matching the aforementioned pattern.

#### Describe the solution you'd like.

A kustomize configuration can "teach" filters to apply transformers to particular field sets. The following setup will substitute images set with `kustomize edit set image key=value` into `.spec.relatedImages` and `RELATED_IMAGE_*` env vars with the right `key`:

```yaml
# config/manifests/relatedimages_config.yaml
images:
# For .spec.relatedImages
- path: spec/relatedImages[]/image
  create: true
# For env vars
- path: spec/install/spec/deployments[]/spec/template/spec/containers[]/env[]/value
  create: true
```

```yaml
# config/manifests/kustomization.yaml
...
configurations:
- relatedimages_config.yaml

# This transformer makes sure the deployment name is set with the right prefix.
# The resulting value will be important for CSV parsing by 'operator-sdk generate bundle'.
transformers:
- |-
  apiVersion: builtin
  kind: PrefixSuffixTransformer
  metadata:
    name: notImportantHere
  prefix: memcached-operator-
  fieldSpecs:
  - path: spec/install/spec/deployments[]/name
    create: false
    kind: ClusterServiceVersion
    group: operators.coreos.com
    version: v1alpha1
```

Given the below base CSV, you can run `kustomize edit set image controller=foo.com/bar@sha256:1234` to create a kustomization.yaml image transformer that maps reference `controller` to `foo.com/bar@sha256:1234`. When you run `kustomize build config/manifests`, you will see a CSV with the expected image reference updates.

<details><summary><code>config/manifests/bases/memcached-operator.csv.yaml</code> contents</summary><br><pre>
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: memcached-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Memcached is the Schema for the memcacheds API
      displayName: Memcached
      kind: Memcached
      name: memcacheds.cache.example.com
      version: v1alpha1
  description: Memcached Operator description. TODO.
  displayName: Memcached Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments:
      - name: controller-manager
        spec:
          template:
            spec:
              containers:
              - name: manager
                env:
                - name: RELATED_IMAGE_FOO_BAR
                  value: controller
                - name: SOME_ENV
                  value: foo
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - memcached-operator
  links:
  - name: Memcached Operator
    url: https://memcached-operator.domain
  maintainers:
  - email: your@email.com
    name: Maintainer Name
  maturity: alpha
  provider:
    name: Provider Name
    url: https://your.domain
  version: 0.0.0
  relatedImages:
  - image: controller
    name: foo_bar
</pre></details>

```diff
@@ -23,17 +23,17 @@
   install:
     spec:
       deployments:
-      - name: controller-manager
+      - name: memcached-operator-controller-manager
         spec:
           template:
             spec:
               containers:
               - name: manager
                 env:
                 - name: RELATED_IMAGE_FOO_BAR
-                  value: controller
+                  value: foo.com/bar@sha256:1234
                 - name: SOME_ENV
                   value: foo
     strategy: deployment
   installModes:
   - supported: false
@@ -56,7 +56,7 @@
   provider:
     name: Provider Name
     url: https://your.domain
   version: 0.0.0
   relatedImages:
-  - image: controller
+  - image: foo.com/bar@sha256:1234
     name: foo_bar
```

To support env vars, some changes are needed in `operator-sdk generate bundle`, namely the ability to merge `RELATED_IMAGE_*` variables into the correct Deployment. This should not be difficult given Deployments and their containers have unique names in this context.
